image: node:8

cache:
  paths:
    - node_modules/

stages:
  - verify
  - deploy

lint:
  stage: verify
  script:
    - npm install
    - npm lint

gl-pages-deploy:
  stage: deploy
  script:
  - npm install
  - npm build
  - npm export
  - rm -rf public
  - mv out public
  - cd public && touch .nojekyll
  artifacts:
    paths:
    - public
  only:
    refs:
      - master
    variables:
      - $DEPLOY_TO_GL_PAGES

