image: node:8

cache:
  paths:
    - node_modules/

stages:
  - verify
  - deploy

lint:
  stage: verify
  script:
    - yarn install
    - yarn run lint

pages:
  stage: deploy
  script:
  - yarn install
  - yarn run build
  - mv out public
  - cd public && touch .nojekyll
  artifacts:
    paths:
    - public
  only:
    refs:
      - master
    variables:
      - $DEPLOY_TO_GL_PAGES

