# NOTES
# - Avoid leading slashes for static resources.

# Team/user/company name. Type: string. Required: no.
name: "John Doe"

# Team/user/company logo. Type: string. Required: no.
logo: "static/logo/logo.png"

# Customize and extend technology icons. Type: object. Required: no.
techIcons:
    react:
      name: "React"
      path: "static/svg/react.svg"
    javascript:
      name: "JavaScript"
      path: "static/svg/js.svg"
    html:
      name: "HTML"
      path: "static/svg/html.svg"

# Customize and extend social icons. Type: object. Required: no.
socialIcons:
  github:
    name: "GitHub"
    path: "static/svg/github.svg"
  medium:
    name: "Medium"
    path: "static/svg/medium.svg"

# Showcase technologies by their icon or name. Type: string, values: "icon" || "name". Required: no.
display: "icon"

# CORS proxy. Required for accessing the Medium API. Use your own! E.g. https://github.com/Rob--W/cors-anywhere. Type: string. Required: no.
proxyURL: "https://cors-anywhere.herokuapp.com/"

# Site header. Type: object. Required: no.
header:
    # Technologies used by team/user/company. Type: array of strings. Required: no.
    technologies:
      - javascript
      - react
    # Team member(s) name and link. Type: array of objects. Required: no.
    teamMembers:
      - name: "Arunoda Susiripala"
        link: "https://twitter.com/arunoda"
    # Team online presence. Type: array of objects. Required:
    socialLinks:
      - name: "github"
        link: "https://github.com/c-hive"
      - name: "medium"
        link: "https://medium.com/c-hive"

# Override the default title. Type: string, default: "Products". Required: no.
productsTitle: "Projects"

# Showcase products. Type: array of objects. Required: no.
products:
  # Product's title. Type: string. Required: yes.
  - name: "Next.JS"

    # Product's cover image. Type: string. Required: no.
    cover: ""

    # Product description. Type: string. Required: no.
    description: "The React Framework"

    # Technologies used by the product. Type: array. Required: no.
    technologies:
      - "react"

    # Product online presence. Type. array of objects. Required: no.
    socialLinks:
      - name: "github"
        link: "https://github.com/zeit/next.js/"

# Aggregate contributions: https://github.com/c-hive/team-contribution-calendar. Type: object. Required: no.
teamContributionCalendarUsers:
  # GitHub users. Type: array of objects. Required: no.
  github:
    - name: "thisismydesign"
      from: "2019-09-22"
    - name: "gomorizsolt"
      from: "2020-01-01"
      to: "2020-04-07"
  # GitLab users. Type: array of objects. Required: no.
  gitlab: []

# Medium identifier. Type: string. Required: no.
medium: "c-hive"

# GitHub identifier. Type: object. Required: no.
github:
  # Organization/user. Type: string. Required: no.
  name: "c-hive"

  # Repository identifiers. Type: array of strings. Required: no.
  repos:
    - "team-contribution-calendar"
    - "ws-anywhere"
    - "js-boilerplate"

  # Percentage threshold for coding languages in a repository to be displayed for the project. Type: number, default: 10. Required: no
  # languageThreshold: 15
