name: CI

on: [push]

env:
  node_version: "12.x"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
      - uses: c-hive/gha-npm-cache@v1
      - name: Install JS dependencies
        run: npm install
      - name: Lint
        run: npm run lint
