name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache JS dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-js-dependencies-${{ hashFiles('**/package-lock.json') }}
          restore-key: |
            ${{ runner.OS }}-js-dependencies-
      - name: Install JS dependencies
        run: npm install
      - name: Lint
        run: npm run lint

  deploy:
    needs: lint
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache JS dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-js-dependencies-${{ hashFiles('**/package-lock.json') }}
          restore-key: |
            ${{ runner.OS }}-js-dependencies-
      - name: Install JS dependencies
        run: npm install
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes" -a
      - name: Build static HTML & Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIGJSON: ${{ secrets.configJSON }}
          BRANCH: gh-pages
          FOLDER: out
          BUILD_SCRIPT: npm run deploy # https://github.com/zeit/next.js/wiki/Deploying-a-Next.js-app-into-GitHub-Pages
