name: Deploy

on:
  push:
    branch:
      - master

env:
  node_version: "12.x"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
      - name: Cache JS dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-js-dependencies-${{ hashFiles('**/package-lock.json') }}
          restore-key: |
            ${{ runner.OS }}-js-dependencies-
      - name: Install JS dependencies
        run: npm install
      - name: Build & Prepare files for deployment
        run: npm run pre:deploy
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FOLDER: out
        env:
          CONFIG: ${{ secrets.CONFIG }}
