name: Deploy

on:
  push:
    branches:
      - master

env:
  node_version: "12.x"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
      - uses: c-hive/gha-npm-cache@v1
      - name: Install JS dependencies
        run: npm install
      - name: Build
        env:
          CONFIG: ${{ secrets.CONFIG }}
        run: npm run build
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases@3.4.9
        with:
          SSH: true
          BRANCH: gh-pages
          FOLDER: out
